name: image_crop
description: A flutter plugin to crop image in insta_assets_picker package. Fork of image_crop package.
version: 0.0.2
homepage: https://github.com/lykhonis/image_crop

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.lykhonis.image_crop
        pluginClass: ImageCropPlugin
      ios:
        pluginClass: ImageCropPlugin
